import About from "./About.jsx"
import Blog from "./Blog.jsx"
import ContactUs from "./ContactUs.jsx"
import Events from "./Events.jsx"
import Error from "./Error.jsx"
import Executives from "./Executives.jsx"
import Home from "./Home.jsx"
import Projects from "./Projects.jsx"
import Academics from "./Academics.jsx"
import Dinner from "./Dinner.jsx"
import Videos from "./Videos.jsx"
import HeartPage from "./Heart.jsx"
import Feedback from "./Feedback.jsx"
import Complaints from "./Complaints.jsx"
import Suggestions from "./Suggestions.jsx"
import Library from "./Library.jsx"

export { About, Blog, ContactUs, Events, Error, Executives, Home, Projects, Academics, Dinner, Videos, HeartPage, Feedback, Complaints, Suggestions, Library }