import About from "./About.jsx"
import Blog from "./Blog.jsx"
import ContactUs from "./ContactUs.jsx"
import Events from "./Events.jsx"
import Error from "./Error.jsx"
import Executives from "./Executives.jsx"
import Home from "./Home.jsx"
import Projects from "./Projects.jsx"
import Academics from "./Academics.jsx"
import FajiLawa from "./FajiLawa.jsx"
import Elections from "./Elections.jsx"
import Apwen from "./Apwen.jsx"
import Feedback from "./Feedback.jsx"
import Complaints from "./Complaints.jsx"
import Suggestions from "./Suggestions.jsx"
import Library from "./Library.jsx"

export { About, Blog, ContactUs, Events, Error, Executives, Home, Projects, Academics, FajiLawa, Elections, Apwen, Feedback, Complaints, Suggestions, Library }